//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.MOVIE_COUNTRY = new HashSet<MOVIE_COUNTRY>();
        }
    
        public decimal COUNTRY_ID { get; set; }
        public string COUNTRY_NAME { get; set; }
    
        public virtual ICollection<MOVIE_COUNTRY> MOVIE_COUNTRY { get; set; }
    }
}
