//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTORS> ACTORS { get; set; }
        public DbSet<COUNTRY> COUNTRY { get; set; }
        public DbSet<FAVORITE> FAVORITE { get; set; }
        public DbSet<GENRE> GENRE { get; set; }
        public DbSet<IMAGES> IMAGES { get; set; }
        public DbSet<MOVIE_COUNTRY> MOVIE_COUNTRY { get; set; }
        public DbSet<MOVIE_SOUNDTRACK> MOVIE_SOUNDTRACK { get; set; }
        public DbSet<MOVIES> MOVIES { get; set; }
        public DbSet<MOVIES_ACTORS> MOVIES_ACTORS { get; set; }
        public DbSet<MOVIES_GENRE> MOVIES_GENRE { get; set; }
        public DbSet<SOUNDTRACK> SOUNDTRACK { get; set; }
        public DbSet<TRAILER> TRAILER { get; set; }
        public DbSet<USERS> USERS { get; set; }
    
        public virtual int DELETEACTOR(Nullable<decimal> pR_ACTOR_ID)
        {
            var pR_ACTOR_IDParameter = pR_ACTOR_ID.HasValue ?
                new ObjectParameter("PR_ACTOR_ID", pR_ACTOR_ID) :
                new ObjectParameter("PR_ACTOR_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEACTOR", pR_ACTOR_IDParameter);
        }
    
        public virtual int DELETECOUNTRY(Nullable<decimal> pR_COUNTRY_ID)
        {
            var pR_COUNTRY_IDParameter = pR_COUNTRY_ID.HasValue ?
                new ObjectParameter("PR_COUNTRY_ID", pR_COUNTRY_ID) :
                new ObjectParameter("PR_COUNTRY_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETECOUNTRY", pR_COUNTRY_IDParameter);
        }
    
        public virtual int DELETEFAVORITE(Nullable<decimal> pR_FAVORITE_ID)
        {
            var pR_FAVORITE_IDParameter = pR_FAVORITE_ID.HasValue ?
                new ObjectParameter("PR_FAVORITE_ID", pR_FAVORITE_ID) :
                new ObjectParameter("PR_FAVORITE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEFAVORITE", pR_FAVORITE_IDParameter);
        }
    
        public virtual int DELETEGENRE(Nullable<decimal> pR_GENRE_ID)
        {
            var pR_GENRE_IDParameter = pR_GENRE_ID.HasValue ?
                new ObjectParameter("PR_GENRE_ID", pR_GENRE_ID) :
                new ObjectParameter("PR_GENRE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEGENRE", pR_GENRE_IDParameter);
        }
    
        public virtual int DELETEIMAGES(Nullable<decimal> pR_IMAGE_ID)
        {
            var pR_IMAGE_IDParameter = pR_IMAGE_ID.HasValue ?
                new ObjectParameter("PR_IMAGE_ID", pR_IMAGE_ID) :
                new ObjectParameter("PR_IMAGE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEIMAGES", pR_IMAGE_IDParameter);
        }
    
        public virtual int DELETEMOVIE_COUNTRY(Nullable<decimal> pR_MOVIE_COUNTRY_ID)
        {
            var pR_MOVIE_COUNTRY_IDParameter = pR_MOVIE_COUNTRY_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_COUNTRY_ID", pR_MOVIE_COUNTRY_ID) :
                new ObjectParameter("PR_MOVIE_COUNTRY_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEMOVIE_COUNTRY", pR_MOVIE_COUNTRY_IDParameter);
        }
    
        public virtual int DELETEMOVIE_GENRE(Nullable<decimal> pR_MOVIE_GENRE_ID)
        {
            var pR_MOVIE_GENRE_IDParameter = pR_MOVIE_GENRE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_GENRE_ID", pR_MOVIE_GENRE_ID) :
                new ObjectParameter("PR_MOVIE_GENRE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEMOVIE_GENRE", pR_MOVIE_GENRE_IDParameter);
        }
    
        public virtual int DELETEMOVIES(Nullable<decimal> pR_MOVIE_ID)
        {
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEMOVIES", pR_MOVIE_IDParameter);
        }
    
        public virtual int DELETEMOVIES_ACTOR(Nullable<decimal> pR_MOVIES_ACTOR_ID)
        {
            var pR_MOVIES_ACTOR_IDParameter = pR_MOVIES_ACTOR_ID.HasValue ?
                new ObjectParameter("PR_MOVIES_ACTOR_ID", pR_MOVIES_ACTOR_ID) :
                new ObjectParameter("PR_MOVIES_ACTOR_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEMOVIES_ACTOR", pR_MOVIES_ACTOR_IDParameter);
        }
    
        public virtual int DELETEMOVIE_SOUNDTRACK(Nullable<decimal> pR_MOVIE_SOUNDTRACK_ID)
        {
            var pR_MOVIE_SOUNDTRACK_IDParameter = pR_MOVIE_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_SOUNDTRACK_ID", pR_MOVIE_SOUNDTRACK_ID) :
                new ObjectParameter("PR_MOVIE_SOUNDTRACK_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEMOVIE_SOUNDTRACK", pR_MOVIE_SOUNDTRACK_IDParameter);
        }
    
        public virtual int DELETESOUNDTRACK(Nullable<decimal> pR_SOUNDTRACK_ID)
        {
            var pR_SOUNDTRACK_IDParameter = pR_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_SOUNDTRACK_ID", pR_SOUNDTRACK_ID) :
                new ObjectParameter("PR_SOUNDTRACK_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETESOUNDTRACK", pR_SOUNDTRACK_IDParameter);
        }
    
        public virtual int DELETETRAILER(Nullable<decimal> pR_TRAILER_ID)
        {
            var pR_TRAILER_IDParameter = pR_TRAILER_ID.HasValue ?
                new ObjectParameter("PR_TRAILER_ID", pR_TRAILER_ID) :
                new ObjectParameter("PR_TRAILER_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETETRAILER", pR_TRAILER_IDParameter);
        }
    
        public virtual int DELETEUSER(Nullable<decimal> pR_USER_ID)
        {
            var pR_USER_IDParameter = pR_USER_ID.HasValue ?
                new ObjectParameter("PR_USER_ID", pR_USER_ID) :
                new ObjectParameter("PR_USER_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEUSER", pR_USER_IDParameter);
        }
    
        public virtual int GET_IMAGE_DIR(Nullable<decimal> pR_IMAGE_ID, ObjectParameter iON)
        {
            var pR_IMAGE_IDParameter = pR_IMAGE_ID.HasValue ?
                new ObjectParameter("PR_IMAGE_ID", pR_IMAGE_ID) :
                new ObjectParameter("PR_IMAGE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_IMAGE_DIR", pR_IMAGE_IDParameter, iON);
        }
    
        public virtual int GET_IMAGE_NAME(Nullable<decimal> pR_IMAGE_ID, ObjectParameter iON)
        {
            var pR_IMAGE_IDParameter = pR_IMAGE_ID.HasValue ?
                new ObjectParameter("PR_IMAGE_ID", pR_IMAGE_ID) :
                new ObjectParameter("PR_IMAGE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_IMAGE_NAME", pR_IMAGE_IDParameter, iON);
        }
    
        public virtual int GET_SOUNDTRACK_DIR(Nullable<decimal> pR_SOUNDTRACK_ID, ObjectParameter iON)
        {
            var pR_SOUNDTRACK_IDParameter = pR_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_SOUNDTRACK_ID", pR_SOUNDTRACK_ID) :
                new ObjectParameter("PR_SOUNDTRACK_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SOUNDTRACK_DIR", pR_SOUNDTRACK_IDParameter, iON);
        }
    
        public virtual int GET_SOUNDTRACK_NAME(Nullable<decimal> pR_SOUNDTRACK_ID, ObjectParameter iON)
        {
            var pR_SOUNDTRACK_IDParameter = pR_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_SOUNDTRACK_ID", pR_SOUNDTRACK_ID) :
                new ObjectParameter("PR_SOUNDTRACK_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SOUNDTRACK_NAME", pR_SOUNDTRACK_IDParameter, iON);
        }
    
        public virtual int GET_TRAILER_DIR(Nullable<decimal> pR_TRAILER_ID, ObjectParameter iON)
        {
            var pR_TRAILER_IDParameter = pR_TRAILER_ID.HasValue ?
                new ObjectParameter("PR_TRAILER_ID", pR_TRAILER_ID) :
                new ObjectParameter("PR_TRAILER_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TRAILER_DIR", pR_TRAILER_IDParameter, iON);
        }
    
        public virtual int GET_TRAILER_NAME(Nullable<decimal> pR_TRAILER_ID, ObjectParameter iON)
        {
            var pR_TRAILER_IDParameter = pR_TRAILER_ID.HasValue ?
                new ObjectParameter("PR_TRAILER_ID", pR_TRAILER_ID) :
                new ObjectParameter("PR_TRAILER_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TRAILER_NAME", pR_TRAILER_IDParameter, iON);
        }
    
        public virtual int INSERFAVORITE(Nullable<decimal> pR_USER_ID, Nullable<decimal> pR_MOVIE_ID, Nullable<decimal> pR_STATUS)
        {
            var pR_USER_IDParameter = pR_USER_ID.HasValue ?
                new ObjectParameter("PR_USER_ID", pR_USER_ID) :
                new ObjectParameter("PR_USER_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            var pR_STATUSParameter = pR_STATUS.HasValue ?
                new ObjectParameter("PR_STATUS", pR_STATUS) :
                new ObjectParameter("PR_STATUS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERFAVORITE", pR_USER_IDParameter, pR_MOVIE_IDParameter, pR_STATUSParameter);
        }
    
        public virtual int INSERTACTOR(string pR_ACTOR_NAME)
        {
            var pR_ACTOR_NAMEParameter = pR_ACTOR_NAME != null ?
                new ObjectParameter("PR_ACTOR_NAME", pR_ACTOR_NAME) :
                new ObjectParameter("PR_ACTOR_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTACTOR", pR_ACTOR_NAMEParameter);
        }
    
        public virtual int INSERTCOUNTRY(string pR_COUNTRY_NAME)
        {
            var pR_COUNTRY_NAMEParameter = pR_COUNTRY_NAME != null ?
                new ObjectParameter("PR_COUNTRY_NAME", pR_COUNTRY_NAME) :
                new ObjectParameter("PR_COUNTRY_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTCOUNTRY", pR_COUNTRY_NAMEParameter);
        }
    
        public virtual int INSERTGENRE(string pR_GENRE_NAME)
        {
            var pR_GENRE_NAMEParameter = pR_GENRE_NAME != null ?
                new ObjectParameter("PR_GENRE_NAME", pR_GENRE_NAME) :
                new ObjectParameter("PR_GENRE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTGENRE", pR_GENRE_NAMEParameter);
        }
    
        public virtual int INSERTIMAGES(string pR_IMAGE_NAME)
        {
            var pR_IMAGE_NAMEParameter = pR_IMAGE_NAME != null ?
                new ObjectParameter("PR_IMAGE_NAME", pR_IMAGE_NAME) :
                new ObjectParameter("PR_IMAGE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTIMAGES", pR_IMAGE_NAMEParameter);
        }
    
        public virtual int INSERTMOVIE_COUNTRY(Nullable<decimal> pR_COUNTRY_ID, Nullable<decimal> pR_MOVIE_ID)
        {
            var pR_COUNTRY_IDParameter = pR_COUNTRY_ID.HasValue ?
                new ObjectParameter("PR_COUNTRY_ID", pR_COUNTRY_ID) :
                new ObjectParameter("PR_COUNTRY_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTMOVIE_COUNTRY", pR_COUNTRY_IDParameter, pR_MOVIE_IDParameter);
        }
    
        public virtual int INSERTMOVIE_GENRE(Nullable<decimal> pR_MOVIE_ID, Nullable<decimal> pR_GENRE_ID)
        {
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            var pR_GENRE_IDParameter = pR_GENRE_ID.HasValue ?
                new ObjectParameter("PR_GENRE_ID", pR_GENRE_ID) :
                new ObjectParameter("PR_GENRE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTMOVIE_GENRE", pR_MOVIE_IDParameter, pR_GENRE_IDParameter);
        }
    
        public virtual int INSERTMOVIES(string pR_MOVIE_NAME, Nullable<System.DateTime> pR_MOVIE_RELISE_DATE, Nullable<decimal> pR_MOVIE_DURATION, string pR_DESCRIPTION)
        {
            var pR_MOVIE_NAMEParameter = pR_MOVIE_NAME != null ?
                new ObjectParameter("PR_MOVIE_NAME", pR_MOVIE_NAME) :
                new ObjectParameter("PR_MOVIE_NAME", typeof(string));
    
            var pR_MOVIE_RELISE_DATEParameter = pR_MOVIE_RELISE_DATE.HasValue ?
                new ObjectParameter("PR_MOVIE_RELISE_DATE", pR_MOVIE_RELISE_DATE) :
                new ObjectParameter("PR_MOVIE_RELISE_DATE", typeof(System.DateTime));
    
            var pR_MOVIE_DURATIONParameter = pR_MOVIE_DURATION.HasValue ?
                new ObjectParameter("PR_MOVIE_DURATION", pR_MOVIE_DURATION) :
                new ObjectParameter("PR_MOVIE_DURATION", typeof(decimal));
    
            var pR_DESCRIPTIONParameter = pR_DESCRIPTION != null ?
                new ObjectParameter("PR_DESCRIPTION", pR_DESCRIPTION) :
                new ObjectParameter("PR_DESCRIPTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTMOVIES", pR_MOVIE_NAMEParameter, pR_MOVIE_RELISE_DATEParameter, pR_MOVIE_DURATIONParameter, pR_DESCRIPTIONParameter);
        }
    
        public virtual int INSERTMOVIES_ACTORS(Nullable<decimal> pR_ACTOR_ID, Nullable<decimal> pR_MOVIE_ID)
        {
            var pR_ACTOR_IDParameter = pR_ACTOR_ID.HasValue ?
                new ObjectParameter("PR_ACTOR_ID", pR_ACTOR_ID) :
                new ObjectParameter("PR_ACTOR_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTMOVIES_ACTORS", pR_ACTOR_IDParameter, pR_MOVIE_IDParameter);
        }
    
        public virtual int INSERTMOVIE_SOUNDTRACK(Nullable<decimal> pR_SOUNDTRACK_ID, Nullable<decimal> pR_MOVIE_ID)
        {
            var pR_SOUNDTRACK_IDParameter = pR_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_SOUNDTRACK_ID", pR_SOUNDTRACK_ID) :
                new ObjectParameter("PR_SOUNDTRACK_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTMOVIE_SOUNDTRACK", pR_SOUNDTRACK_IDParameter, pR_MOVIE_IDParameter);
        }
    
        public virtual int INSERTSOUNDTRACK(string pR_SOUNDTRACK_NAME)
        {
            var pR_SOUNDTRACK_NAMEParameter = pR_SOUNDTRACK_NAME != null ?
                new ObjectParameter("PR_SOUNDTRACK_NAME", pR_SOUNDTRACK_NAME) :
                new ObjectParameter("PR_SOUNDTRACK_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTSOUNDTRACK", pR_SOUNDTRACK_NAMEParameter);
        }
    
        public virtual int INSERTTRAILER(string pR_TRAILER_NAME)
        {
            var pR_TRAILER_NAMEParameter = pR_TRAILER_NAME != null ?
                new ObjectParameter("PR_TRAILER_NAME", pR_TRAILER_NAME) :
                new ObjectParameter("PR_TRAILER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTTRAILER", pR_TRAILER_NAMEParameter);
        }
    
        public virtual int INSERTUSER(string pR_USER_NAME, string pR_USERS_LASTNAME, string pR_USERS_EMAIL, string pR_USERS_PASSWORD)
        {
            var pR_USER_NAMEParameter = pR_USER_NAME != null ?
                new ObjectParameter("PR_USER_NAME", pR_USER_NAME) :
                new ObjectParameter("PR_USER_NAME", typeof(string));
    
            var pR_USERS_LASTNAMEParameter = pR_USERS_LASTNAME != null ?
                new ObjectParameter("PR_USERS_LASTNAME", pR_USERS_LASTNAME) :
                new ObjectParameter("PR_USERS_LASTNAME", typeof(string));
    
            var pR_USERS_EMAILParameter = pR_USERS_EMAIL != null ?
                new ObjectParameter("PR_USERS_EMAIL", pR_USERS_EMAIL) :
                new ObjectParameter("PR_USERS_EMAIL", typeof(string));
    
            var pR_USERS_PASSWORDParameter = pR_USERS_PASSWORD != null ?
                new ObjectParameter("PR_USERS_PASSWORD", pR_USERS_PASSWORD) :
                new ObjectParameter("PR_USERS_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTUSER", pR_USER_NAMEParameter, pR_USERS_LASTNAMEParameter, pR_USERS_EMAILParameter, pR_USERS_PASSWORDParameter);
        }
    
        public virtual int UPDATEACTOR(Nullable<decimal> pR_ACTOR_ID, string pR_ACTOR_NAME)
        {
            var pR_ACTOR_IDParameter = pR_ACTOR_ID.HasValue ?
                new ObjectParameter("PR_ACTOR_ID", pR_ACTOR_ID) :
                new ObjectParameter("PR_ACTOR_ID", typeof(decimal));
    
            var pR_ACTOR_NAMEParameter = pR_ACTOR_NAME != null ?
                new ObjectParameter("PR_ACTOR_NAME", pR_ACTOR_NAME) :
                new ObjectParameter("PR_ACTOR_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEACTOR", pR_ACTOR_IDParameter, pR_ACTOR_NAMEParameter);
        }
    
        public virtual int UPDATECOUNTRY(Nullable<decimal> pR_COUNTRY_ID, string pR_COUNTRY_NAME)
        {
            var pR_COUNTRY_IDParameter = pR_COUNTRY_ID.HasValue ?
                new ObjectParameter("PR_COUNTRY_ID", pR_COUNTRY_ID) :
                new ObjectParameter("PR_COUNTRY_ID", typeof(decimal));
    
            var pR_COUNTRY_NAMEParameter = pR_COUNTRY_NAME != null ?
                new ObjectParameter("PR_COUNTRY_NAME", pR_COUNTRY_NAME) :
                new ObjectParameter("PR_COUNTRY_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATECOUNTRY", pR_COUNTRY_IDParameter, pR_COUNTRY_NAMEParameter);
        }
    
        public virtual int UPDATEFAVORITE(Nullable<decimal> pR_FAVORITE_ID, Nullable<decimal> pR_USER_ID, Nullable<decimal> pR_MOVIE_ID, Nullable<decimal> pR_STATUS)
        {
            var pR_FAVORITE_IDParameter = pR_FAVORITE_ID.HasValue ?
                new ObjectParameter("PR_FAVORITE_ID", pR_FAVORITE_ID) :
                new ObjectParameter("PR_FAVORITE_ID", typeof(decimal));
    
            var pR_USER_IDParameter = pR_USER_ID.HasValue ?
                new ObjectParameter("PR_USER_ID", pR_USER_ID) :
                new ObjectParameter("PR_USER_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            var pR_STATUSParameter = pR_STATUS.HasValue ?
                new ObjectParameter("PR_STATUS", pR_STATUS) :
                new ObjectParameter("PR_STATUS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEFAVORITE", pR_FAVORITE_IDParameter, pR_USER_IDParameter, pR_MOVIE_IDParameter, pR_STATUSParameter);
        }
    
        public virtual int UPDATEGENRE(Nullable<decimal> pR_GENRE_ID, string pR_GENRE_NAME)
        {
            var pR_GENRE_IDParameter = pR_GENRE_ID.HasValue ?
                new ObjectParameter("PR_GENRE_ID", pR_GENRE_ID) :
                new ObjectParameter("PR_GENRE_ID", typeof(decimal));
    
            var pR_GENRE_NAMEParameter = pR_GENRE_NAME != null ?
                new ObjectParameter("PR_GENRE_NAME", pR_GENRE_NAME) :
                new ObjectParameter("PR_GENRE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEGENRE", pR_GENRE_IDParameter, pR_GENRE_NAMEParameter);
        }
    
        public virtual int UPDATEIMAGES(Nullable<decimal> pR_IMAGE_ID, string pR_IMAGE_NAME)
        {
            var pR_IMAGE_IDParameter = pR_IMAGE_ID.HasValue ?
                new ObjectParameter("PR_IMAGE_ID", pR_IMAGE_ID) :
                new ObjectParameter("PR_IMAGE_ID", typeof(decimal));
    
            var pR_IMAGE_NAMEParameter = pR_IMAGE_NAME != null ?
                new ObjectParameter("PR_IMAGE_NAME", pR_IMAGE_NAME) :
                new ObjectParameter("PR_IMAGE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEIMAGES", pR_IMAGE_IDParameter, pR_IMAGE_NAMEParameter);
        }
    
        public virtual int UPDATEMOVIE_COUNTRY(Nullable<decimal> pR_MOVIE_COUNTRY_ID, Nullable<decimal> pR_COUNTRY_ID, Nullable<decimal> pR_MOVIE_ID)
        {
            var pR_MOVIE_COUNTRY_IDParameter = pR_MOVIE_COUNTRY_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_COUNTRY_ID", pR_MOVIE_COUNTRY_ID) :
                new ObjectParameter("PR_MOVIE_COUNTRY_ID", typeof(decimal));
    
            var pR_COUNTRY_IDParameter = pR_COUNTRY_ID.HasValue ?
                new ObjectParameter("PR_COUNTRY_ID", pR_COUNTRY_ID) :
                new ObjectParameter("PR_COUNTRY_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEMOVIE_COUNTRY", pR_MOVIE_COUNTRY_IDParameter, pR_COUNTRY_IDParameter, pR_MOVIE_IDParameter);
        }
    
        public virtual int UPDATEMOVIE_GENRE(Nullable<decimal> pR_MOVIE_GENRE_ID, Nullable<decimal> pR_MOVIE_ID, Nullable<decimal> pR_GENRE_ID)
        {
            var pR_MOVIE_GENRE_IDParameter = pR_MOVIE_GENRE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_GENRE_ID", pR_MOVIE_GENRE_ID) :
                new ObjectParameter("PR_MOVIE_GENRE_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            var pR_GENRE_IDParameter = pR_GENRE_ID.HasValue ?
                new ObjectParameter("PR_GENRE_ID", pR_GENRE_ID) :
                new ObjectParameter("PR_GENRE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEMOVIE_GENRE", pR_MOVIE_GENRE_IDParameter, pR_MOVIE_IDParameter, pR_GENRE_IDParameter);
        }
    
        public virtual int UPDATEMOVIES(Nullable<decimal> pR_MOVIE_ID, string pR_MOVIE_NAME, Nullable<System.DateTime> pR_MOVIE_RELISE_DATE, Nullable<decimal> pR_MOVIE_DURATION, string pR_DESCRIPTION)
        {
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            var pR_MOVIE_NAMEParameter = pR_MOVIE_NAME != null ?
                new ObjectParameter("PR_MOVIE_NAME", pR_MOVIE_NAME) :
                new ObjectParameter("PR_MOVIE_NAME", typeof(string));
    
            var pR_MOVIE_RELISE_DATEParameter = pR_MOVIE_RELISE_DATE.HasValue ?
                new ObjectParameter("PR_MOVIE_RELISE_DATE", pR_MOVIE_RELISE_DATE) :
                new ObjectParameter("PR_MOVIE_RELISE_DATE", typeof(System.DateTime));
    
            var pR_MOVIE_DURATIONParameter = pR_MOVIE_DURATION.HasValue ?
                new ObjectParameter("PR_MOVIE_DURATION", pR_MOVIE_DURATION) :
                new ObjectParameter("PR_MOVIE_DURATION", typeof(decimal));
    
            var pR_DESCRIPTIONParameter = pR_DESCRIPTION != null ?
                new ObjectParameter("PR_DESCRIPTION", pR_DESCRIPTION) :
                new ObjectParameter("PR_DESCRIPTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEMOVIES", pR_MOVIE_IDParameter, pR_MOVIE_NAMEParameter, pR_MOVIE_RELISE_DATEParameter, pR_MOVIE_DURATIONParameter, pR_DESCRIPTIONParameter);
        }
    
        public virtual int UPDATEMOVIES_ACTORS(Nullable<decimal> pR_MOVIES_ACTOR_ID, Nullable<decimal> pR_ACTOR_ID, Nullable<decimal> pR_MOVIE_ID)
        {
            var pR_MOVIES_ACTOR_IDParameter = pR_MOVIES_ACTOR_ID.HasValue ?
                new ObjectParameter("PR_MOVIES_ACTOR_ID", pR_MOVIES_ACTOR_ID) :
                new ObjectParameter("PR_MOVIES_ACTOR_ID", typeof(decimal));
    
            var pR_ACTOR_IDParameter = pR_ACTOR_ID.HasValue ?
                new ObjectParameter("PR_ACTOR_ID", pR_ACTOR_ID) :
                new ObjectParameter("PR_ACTOR_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEMOVIES_ACTORS", pR_MOVIES_ACTOR_IDParameter, pR_ACTOR_IDParameter, pR_MOVIE_IDParameter);
        }
    
        public virtual int UPDATEMOVIE_SOUNDTRACK(Nullable<decimal> pR_MOVIE_SOUNDTRACK_ID, Nullable<decimal> pR_SOUNDTRACK_ID, Nullable<decimal> pR_MOVIE_ID)
        {
            var pR_MOVIE_SOUNDTRACK_IDParameter = pR_MOVIE_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_SOUNDTRACK_ID", pR_MOVIE_SOUNDTRACK_ID) :
                new ObjectParameter("PR_MOVIE_SOUNDTRACK_ID", typeof(decimal));
    
            var pR_SOUNDTRACK_IDParameter = pR_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_SOUNDTRACK_ID", pR_SOUNDTRACK_ID) :
                new ObjectParameter("PR_SOUNDTRACK_ID", typeof(decimal));
    
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEMOVIE_SOUNDTRACK", pR_MOVIE_SOUNDTRACK_IDParameter, pR_SOUNDTRACK_IDParameter, pR_MOVIE_IDParameter);
        }
    
        public virtual int UPDATESOUNDTRACK(Nullable<decimal> pR_SOUNDTRACK_ID, string pR_SOUNDTRACK_NAME)
        {
            var pR_SOUNDTRACK_IDParameter = pR_SOUNDTRACK_ID.HasValue ?
                new ObjectParameter("PR_SOUNDTRACK_ID", pR_SOUNDTRACK_ID) :
                new ObjectParameter("PR_SOUNDTRACK_ID", typeof(decimal));
    
            var pR_SOUNDTRACK_NAMEParameter = pR_SOUNDTRACK_NAME != null ?
                new ObjectParameter("PR_SOUNDTRACK_NAME", pR_SOUNDTRACK_NAME) :
                new ObjectParameter("PR_SOUNDTRACK_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATESOUNDTRACK", pR_SOUNDTRACK_IDParameter, pR_SOUNDTRACK_NAMEParameter);
        }
    
        public virtual int UPDATETRAILER(Nullable<decimal> pR_TRAILER_ID, string pR_TRAILER_NAME)
        {
            var pR_TRAILER_IDParameter = pR_TRAILER_ID.HasValue ?
                new ObjectParameter("PR_TRAILER_ID", pR_TRAILER_ID) :
                new ObjectParameter("PR_TRAILER_ID", typeof(decimal));
    
            var pR_TRAILER_NAMEParameter = pR_TRAILER_NAME != null ?
                new ObjectParameter("PR_TRAILER_NAME", pR_TRAILER_NAME) :
                new ObjectParameter("PR_TRAILER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATETRAILER", pR_TRAILER_IDParameter, pR_TRAILER_NAMEParameter);
        }
    
        public virtual int UPDATEUSER(Nullable<decimal> pR_USER_ID, string pR_USER_NAME, string pR_USERS_LASTNAME, string pR_USERS_EMAIL, string pR_USERS_PASSWORD)
        {
            var pR_USER_IDParameter = pR_USER_ID.HasValue ?
                new ObjectParameter("PR_USER_ID", pR_USER_ID) :
                new ObjectParameter("PR_USER_ID", typeof(decimal));
    
            var pR_USER_NAMEParameter = pR_USER_NAME != null ?
                new ObjectParameter("PR_USER_NAME", pR_USER_NAME) :
                new ObjectParameter("PR_USER_NAME", typeof(string));
    
            var pR_USERS_LASTNAMEParameter = pR_USERS_LASTNAME != null ?
                new ObjectParameter("PR_USERS_LASTNAME", pR_USERS_LASTNAME) :
                new ObjectParameter("PR_USERS_LASTNAME", typeof(string));
    
            var pR_USERS_EMAILParameter = pR_USERS_EMAIL != null ?
                new ObjectParameter("PR_USERS_EMAIL", pR_USERS_EMAIL) :
                new ObjectParameter("PR_USERS_EMAIL", typeof(string));
    
            var pR_USERS_PASSWORDParameter = pR_USERS_PASSWORD != null ?
                new ObjectParameter("PR_USERS_PASSWORD", pR_USERS_PASSWORD) :
                new ObjectParameter("PR_USERS_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEUSER", pR_USER_IDParameter, pR_USER_NAMEParameter, pR_USERS_LASTNAMEParameter, pR_USERS_EMAILParameter, pR_USERS_PASSWORDParameter);
        }
    
        public virtual int GET_MOVIE_DESCRIPTION(Nullable<decimal> pR_MOVIE_ID, ObjectParameter iON)
        {
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_MOVIE_DESCRIPTION", pR_MOVIE_IDParameter, iON);
        }
    
        public virtual int GET_MOVIE_NAME(Nullable<decimal> pR_MOVIE_ID, ObjectParameter iON)
        {
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_MOVIE_NAME", pR_MOVIE_IDParameter, iON);
        }
    
        public virtual int SEARCH_FILM(string pR_MOVIE_NAME, ObjectParameter pR_MOVIE_ID)
        {
            var pR_MOVIE_NAMEParameter = pR_MOVIE_NAME != null ?
                new ObjectParameter("PR_MOVIE_NAME", pR_MOVIE_NAME) :
                new ObjectParameter("PR_MOVIE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEARCH_FILM", pR_MOVIE_NAMEParameter, pR_MOVIE_ID);
        }
    
        public virtual int GET_MOVIE_EYAR(Nullable<decimal> pR_MOVIE_ID, ObjectParameter iON)
        {
            var pR_MOVIE_IDParameter = pR_MOVIE_ID.HasValue ?
                new ObjectParameter("PR_MOVIE_ID", pR_MOVIE_ID) :
                new ObjectParameter("PR_MOVIE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_MOVIE_EYAR", pR_MOVIE_IDParameter, iON);
        }
    }
}
