//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITE
    {
        public decimal ID { get; set; }
        public decimal USER_ID { get; set; }
        public decimal MOVIE_ID { get; set; }
        public string STATUS { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual MOVIES MOVIES { get; set; }
    }
}
