//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENRE
    {
        public GENRE()
        {
            this.MOVIES_GENRE = new HashSet<MOVIES_GENRE>();
        }
    
        public decimal GENRE_ID { get; set; }
        public string GENRE_NAME { get; set; }
    
        public virtual ICollection<MOVIES_GENRE> MOVIES_GENRE { get; set; }
    }
}
