//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGES
    {
        public decimal IMAGE_ID { get; set; }
        public string IMAGE_NAME { get; set; }
        public byte[] IMAGE { get; set; }
    
        public virtual MOVIES MOVIES { get; set; }
    }
}
