//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUNDTRACK
    {
        public SOUNDTRACK()
        {
            this.MOVIE_SOUNDTRACK = new HashSet<MOVIE_SOUNDTRACK>();
        }
    
        public decimal SOUNDTRACK_ID { get; set; }
        public string SOUNDTRACK_NAME { get; set; }
        public byte[] SOUNDTRACK1 { get; set; }
    
        public virtual ICollection<MOVIE_SOUNDTRACK> MOVIE_SOUNDTRACK { get; set; }
    }
}
