//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.FAVORITE = new HashSet<FAVORITE>();
        }
    
        public decimal USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_LASTNAME { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_PASSWORD { get; set; }
    
        public virtual ICollection<FAVORITE> FAVORITE { get; set; }
    }
}
